language: node_js
node_js:
  - node
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
