language: node_js

node_js:
  - node

branches:
  only:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  yarn: true
  directories:
    - node_modules

install:
  - npm install -g firebase-tools

script:
  - yarn
  - yarn run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
